/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* define to use back slash */
/* #undef BACK_SLASH */

/* Text mode only */
/* #undef BASIC */

/* define to use buffered debug output */
/* #undef BUFFERED_LOG */

/* define to allow sound clipping */
/* #undef CLIP_SOUND */

/* Define to 1 if the `closedir' function returns void instead of `int'. */
/* #undef CLOSEDIR_VOID */

/* define to allow console sound (keyboard clicks) */
/* #undef CONSOLE_SOUND */

/* define to activate crash menu after CIM instruction */
#define CRASH_MENU 

/* define to allow color changes inside a scanline */
#define CYCLE_EXACT 

/* alternate config filename due to 8+3 fs limit */
/* #undef DEFAULT_CFG_NAME */

/* Windows with DirectX */
/* #undef DIRECTX */

/* DOS vga */
/* #undef DOSVGA */

/* define to enable dos style drives support */
/* #undef DOS_DRIVES */

/* Atari Falcon system */
/* #undef FALCON */

/* define to use m68k assembler CPU core for Falcon target */
/* #undef FALCON_CPUASM */

/* Define to 1 if you have the <arpa/inet.h> header file. */
#define HAVE_ARPA_INET_H 1

/* Define to 1 if you have the `atexit' function. */
#define HAVE_ATEXIT 1

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#define HAVE_DIRENT_H 1

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `floor' function. */
#define HAVE_FLOOR 1

/* Define to 1 if you have the `getcwd' function. */
#define HAVE_GETCWD 1

/* Define to 1 if you have the `gethostbyaddr' function. */
/* #undef HAVE_GETHOSTBYADDR */

/* Define to 1 if you have the `gethostbyname' function. */
/* #undef HAVE_GETHOSTBYNAME */

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the `inet_ntoa' function. */
/* #undef HAVE_INET_NTOA */

/* Define to 1 if you have the <inttypes.h> header file. */
/* #undef HAVE_INTTYPES_H */

/* Define to 1 if you have the `z' library (-lz). */
/* #undef HAVE_LIBZ */

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if your system has a GNU libc compatible `malloc' function, and
   to 0 otherwise. */
#define HAVE_MALLOC 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `memset' function. */
#define HAVE_MEMSET 1

/* Define to 1 if you have the `mkdir' function. */
#define HAVE_MKDIR 1

/* Define to 1 if you have the `mkstemp' function. */
#define HAVE_MKSTEMP 1

/* Define to 1 if you have the `modf' function. */
#define HAVE_MODF 1

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the <netdb.h> header file. */
#define HAVE_NETDB_H 1

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define to 1 if you have the <OS.h> header file. */
/* #undef HAVE_OS_H */

/* Define to 1 if you have the `rmdir' function. */
#define HAVE_RMDIR 1

/* Define to 1 if you have the `select' function. */
#define HAVE_SELECT 1

/* Define to 1 if you have the `socket' function. */
/* #undef HAVE_SOCKET */

/* Define to 1 if `stat' has the bug that it succeeds when given the
   zero-length file name argument. */
/* #undef HAVE_STAT_EMPTY_STRING_BUG */

/* Define to 1 if you have the <stdint.h> header file. */
/* #undef HAVE_STDINT_H */

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcasecmp' function. */
/* #undef HAVE_STRCASECMP */

/* Define to 1 if you have the `strchr' function. */
#define HAVE_STRCHR 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strrchr' function. */
#define HAVE_STRRCHR 1

/* Define to 1 if you have the `strstr' function. */
#define HAVE_STRSTR 1

/* Define to 1 if you have the `strtol' function. */
#define HAVE_STRTOL 1

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/select.h> header file. */
#define HAVE_SYS_SELECT_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* define to allow sound interpolation */
/* #undef INTERPOLATE_SOUND */

/* define to use LINUX joystick */
/* #undef LINUX_JOYSTICK */

/* Define to 1 if `lstat' dereferences a symlink specified with a trailing
   slash. */
/* #undef LSTAT_FOLLOWS_SLASHED_SYMLINK */

/* define to activate assembler in monitor */
#define MONITOR_ASSEMBLER 

/* define to activate BREAK command in monitor */
#define MONITOR_BREAK 

/* define to activate hints in disassembler */
#define MONITOR_HINTS 

/* X11 with Motif */
/* #undef MOTIF */

/* define to allow new cycle-exact scanline routines */
#define NEW_CYCLE_EXACT 

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "pstehlik@sophics.cz"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Atari800"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Atari800 1.3.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "atari800"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.3.2"

/* define to use page-based attribute array */
/* #undef PAGED_ATTRIB */

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* define to use R: device */
/* #undef R_IO_DEVICE */

/* System with SDL library */
/* #undef SDL */

/* Define to the type of arg 1 for `select'. */
#define SELECT_TYPE_ARG1 int

/* Define to the type of args 2, 3 and 4 for `select'. */
#define SELECT_TYPE_ARG234 (fd_set *)

/* Define to the type of arg 5 for `select'. */
#define SELECT_TYPE_ARG5 (struct timeval *)

/* define to allow serial in/out sound */
/* #undef SERIO_SOUND */

/* X11 with shared memory extensions */
/* #undef SHM */

/* define to show disk LED emulation on screen display */
#define SHOW_DISK_LED 

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* define to use snailmeter */
/* #undef SNAILMETER */

/* define to activate sound support */
/* #undef SOUND */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* define to allow stereo sound */
/* #undef STEREO_SOUND */

/* Save additional config file options */
/* #undef SUPPORTS_ATARI_CONFIGSAVE */

/* Additional config file options */
/* #undef SUPPORTS_ATARI_CONFIGURE */

/* Linux with SVGALib */
/* #undef SVGALIB */

/* define to use Toshiba Joystick Mouse support */
/* #undef SVGA_JOYMOUSE */

/* define for drawing every 1/50 sec only 1/refresh of screen */
/* #undef SVGA_SPEEDUP */

/* alternate system-wide config file for non-Unix OS */
/* #undef SYSTEM_WIDE_CFG_FILE */

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Define to 1 if your <sys/time.h> declares `struct tm'. */
/* #undef TM_IN_SYS_TIME */

/* define if unaligned long access is ok */
#define UNALIGNED_LONG_OK 

/* define to use clock() instead of gettimeofday() */
/* #undef USE_CLOCK */

/* System with Curses library */
/* #undef USE_CURSES */

/* define using cursor/ctrl keys for keyboard joystick */
/* #undef USE_CURSORBLOCK */

/* System with Ncurses library */
/* #undef USE_NCURSES */

/* define to use very slow computer support */
/* #undef VERY_SLOW */

/* define to allow stereo sound */
/* #undef VOL_ONLY_SOUND */

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Standard X11 */
#define X11 

/* X11 with XView */
/* #undef XVIEW */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to rpl_malloc if the replacement function should be used. */
/* #undef malloc */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to empty if the keyword `volatile' does not work. Warning: valid
   code using `volatile' can become incorrect without. Disable with care. */
/* #undef volatile */
